Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,5 +17,25 @@ jobs:
                echo "SNYK_OAUTH_TOKEN=$TOKEN" >> $GITHUB_ENV
       - uses: snyk/actions/setup@master
       - uses: actions/checkout@v3
+
+      
+      - name: setup jdk 8
+        uses: actions/setup-java@v4
+        with:
+          distribution: 'zulu'
+          java-version: 8
+          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
+          settings-path: ${{ github.workspace }} # location for the settings.xml file
+
+      - name: unit tests
+        run: mvn -B test --file pom.xml
+
+      - name: build the app
+        run: |
+          mvn clean
+          mvn -B package --file pom.xml
+
+        # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
+        # Use || true to not fail the pipeline
       - name: Run snyk test
         run: snyk test
